### PR TITLE
Tier vs Salary comparision by Sai Karthik

### PR DESCRIPTION
**Pull request by kasaikarthik**
Hey! I've added a new plot of Tier of the college vs Salary comparision

### CODE REVIEW

**Comment by vj68** [comment]
@kasaikarthik , Nice plot! But I couldn't locate the code which makes that plot.

**Comment by kasaikarthik** [comment]
Hey! The script is script1.ipynb, located in the scripts folder. I used an
ipynb file, for convenience.

**Comment by vj68** [comment]
This is the only code I see @kasaikarthik , in [script1.ipynb](https://github.com/kasaikarthik/India-data-visualisation/blob/viz1/engineers-employability/scripts/script1.ipynb) . How do you make the plot?

```python
import pandas as pd 

import matplotlib.pyplot as plt


#load dataset
data = pd.read_csv("engineers-employability/data/data.csv")
```

**Comment by kasaikarthik** [comment]
Hey! Looks like I missed out on updating the script1.ipynb file before
commiting to the remote. I've given a new pull request, do look into it.

**Pull request merged**
